fonts_pygame = ['dejavuserif', 'notosansthai', 'notosansmodi', 'urwbookman', 'freesans', 'notosanspahawhhmong',
                'notoserifyezidi', 'notosansoldnortharabian', 'dejavusansmono', 'pxtandyoldtv2y', 'notosanscypriot',
                'ubuntu', 'notosanspsalterpahlavi', 'ubuntusans', 'notosanswarangciti', 'notosanslisu',
                'notosanssogdian', 'pxvtechbios2y', 'notosansmongolian', 'dejavusans', 'notosanslimbu',
                'notoserifcjksc', 'nimbusmonops', 'notosansugaritic', 'notosansmono', 'notosanskhmer',
                'notoserifcjktc', 'pxibm3270pc', 'notosansarmenian', 'notosansgujarati', 'p052',
                'liberationsansnarrow', 'notosansoriya', 'notosanswancho', 'notosanscaucasianalbanian',
                'notoserifhebrew', 'notosansinscriptionalparthian', 'nimbussans', 'notosansmayannumerals',
                'notosanstakri', 'notosansadlamunjoined', 'notosanssignwriting', 'notonaskharabic',
                'notosanstifinaghhawad', 'pxtandyold225', 'pxati8x82y', 'nimbussansnarrow', 'notoseriftelugu',
                'notosanscuneiform', 'pxcompaqthin8x14', 'notorashihebrew', 'notoserifcjkjp', 'notoserifcjkhk',
                'notoserifcjkkr', 'c059', 'pxittbios2y', 'freemono', 'liberationsans', 'notoseriftamil',
                'leaguespartan', 'pxcompaqthin8x16', 'pxtandynewmono', 'notosanssyriac', 'notosanscjkjp',
                'liberationmono', 'pxamibios', 'notosanscjkhk', 'notosanscjkkr', 'notosanstifinagh',
                'notosanssorasompeng', 'notoserifdisplay', 'notosansolchiki', 'pxibmcga', 'notoserifbalinese',
                'notosansmyanmar', 'liberationserif', 'notoserifgurmukhi', 'notoloopedthai', 'notosansmarchen',
                'notosanssaurashtra', 'agave', 'notoserifahom', 'notoserifbengali', 'notosanstifinaghtawellemmet',
                'notosanscjksc', 'notosansbamum', 'pxati8x16', 'pxibmconv', 'notosanscjktc', 'notosansrunic',
                'pxibmmda', 'notoserifkhojki', 'notosansnewtailue', 'pxtandyoldtv', 'ubuntumono', 'notokufiarabic',
                'pxati8x14', 'notosansoldsogdian', 'pxphoenixega8x14', 'notoserifgujarati', 'fontawesome',
                'pxibmvga9', 'notoserifarmenian', 'pxibmpgc2x', 'notosanscanadianaboriginal', 'notosansbalinese',
                'ubuntusansmono', 'notosans', 'notosanstifinaghair', 'z003', 'vlpgothic', 'pxibmvga8', 'urwgothic',
                'notosansbhaiksuki', 'notoserifkhmer', 'notosansjavanese', 'pxphoenixega8x16', 'pxattpc6300',
                'notoserifmalayalam', 'notosansdisplay', 'notosanslinearb', 'notosanskannada', 'notosanslycian',
                'notosansshavian', 'notosansbengali', 'gentiumalt', 'notosanskhudawadi', 'notosansyi',
                'notosanslineara', 'notosansinscriptionalpahlavi', 'd050000l', 'notoserifdogra', 'freeserif',
                'notosanslydian', 'notosanstagalog', 'pxtandynewtv', 'notosansosmanya', 'notosanshanunoo',
                'notosansdevanagari', 'notosansmeeteimayek', 'notoserifgrantha', 'pxverite8x8', 'pxibmconv2x',
                'notosansethiopic', 'notosansoldsoutharabian', 'notosanselbasan', 'notoserifmyanmar',
                'notosansgeorgian', 'pxibmconv2y', 'notoseriftangut', 'notosanstifinaghadrar', 'ibm3270condensed',
                'notosansgrantha', 'notosansbassavah', 'nimbusroman', 'notoserifethiopic', 'pxibmcgathin',
                'notosansgurmukhi', 'notoserifsinhala', 'notosanskharoshthi', 'pxibmvga82x', 'notosansrejang',
                'pxverite9x16', 'vlgothic', 'notosansmedefaidrin', 'pxamstradpc15122y', 'notoserifhmongnyiakeng',
                'dejavumathtexgyre', 'notoserif', 'notosansnushu', 'droidsansfallback', 'notoserifdevanagari',
                'amiga', 'pxverite9x14', 'notosanstaiviet', 'notosansduployan', 'notosansbuhid', 'notosansthaana',
                'notosansmro', 'notosanstamil', 'pxibmega9', 'notosanskayahli', 'notosansnko', 'notosansdeseret',
                'notosanssundanese', 'pxati9x16', 'notosansosage', 'pxibmega8', 'pxdtkbios', 'pxibmega82x',
                'notosanscham', 'notosanstifinaghazawagh', 'pxvtechbios', 'notoseriftamilslanted', 'notosanslepcha',
                'notosanslao', 'pxati9x14', 'notosansmiao', 'notosanstifinaghapt', 'notosanshanifirohingya',
                'notoserifgeorgian', 'notosansoldturkic', 'pxibmcga2y', 'notoseriflao', 'pxdtkbios2y', 'notosansnewa',
                'notomusic', 'notosansegyptianhieroglyphs', 'notosansimperialaramaic', 'pxittbios', 'pxtandynew2252y',
                'notosansmath', 'notosanstirhuta', 'notosanstifinaghghat', 'notosansbuginese', 'pxtoshibalcd8x16',
                'pxamstradpc1512', 'notosansolditalic', 'notoserifthai', 'nototraditionalnushu',
                'notosansmasaramgondi', 'notosanssylotinagri', 'pxattpc63002x', 'notosansavestan', 'notosanssinhala',
                'atari800', 'ibm3270', 'pxcompaqthin8x8', 'notosansoldpermic', 'notosanspalmyrene',
                'notosansmalayalam', 'pxtandyold2252y', 'pxphoenixbios', 'notosanskhojki', 'pxphoenixega8x8',
                'pxibmvga92x', 'pxverite8x16', 'notonastaliqurdu', 'notosanssoyombo', 'notosanspaucinhau',
                'notosansgothic', 'notosanssamaritan', 'notosanscoptic', 'pxverite8x14', 'pxtoshibalcd8x8',
                'notosanskaithi', 'notosanstagbanwa', 'pxkaypro2k2y', 'notosansadlam', 'notosansmeroitic',
                'pxwyse700b', 'gentium', 'notosansmonocjktc', 'pxibmega92x', 'notoserifkannada',
                'notosanstifinaghahaggar', 'notosansmonocjksc', 'pxwyse700a', 'pxati8x8', 'notosansgunjalagondi',
                'notosansmonocjkkr', 'notosansmonocjkhk', 'notosansarabic', 'notosansmonocjkjp', 'pxwyse700a2y',
                'notosanstamilsupplement', 'pxibmiso8', 'notosansoldpersian', 'pxibmpgc',
                'notosansanatolianhieroglyphs', 'notosanssymbols2', 'pxibmiso9', 'notosansmanichaean',
                'notoloopedlao', 'notosansbatak', 'notosanssharada', 'notosanstaitham', 'pxphoenixega8x82y',
                'notosanshatran', 'notosansmultani', 'pxkaypro2k', 'pxibmps2thin4', 'standardsymbolsps',
                'pxvgasquarepx', 'pxphoenixbios2y', 'pxibmbios', 'notosanscarian', 'notomono', 'pxamibios2y',
                'notosanschakma', 'pxibmps2thin2', 'notoseriftibetan', 'notosanszanabazarsquare', 'notosanscherokee',
                'pxibmps2thin3', 'pxibmbios2x', 'notosansbrahmi', 'notosanssymbols', 'notosansmendekikakui',
                'notosansvai', 'pxibmbios2y', 'notosanselymaic', 'pxibmps2thin1', 'pxtandynewtv2y', 'c64',
                'notosanstelugu', 'pxverite8x82y', 'notocoloremoji', 'notosanshebrew', 'notosansmandaic',
                'notosansmahajani', 'notosansoldhungarian', 'ibm3270semicondensed', 'notosansindicsiyaqnumbers',
                'notosanstifinaghsil', 'notosanssiddham', 'notosansogham', 'inconsolata', 'notosanstaile',
                'notosansphagspa', 'notosansphoenician', 'pxatismallw6x8', 'pxwyse700b2y',
                'notosanstifinaghagrawimazighen', 'pxtandynew225', 'pxibmcgathin2y', 'notosanstifinaghrhissaixa',
                'pxphoenixega9x14', 'notosansglagolitic', 'notosansnabataean']

length = len(fonts_pygame)
fonts_list = {}
for n in range(length):
    fonts_list[n] = fonts_pygame[n]

print(fonts_list)